### ISSUE TITLE
Add dragTo funtionality between points.

### ISSUE THREAD

**Issue by dingusagar** [dingusagar/pyautoeasy#12]
```
point1 = ScreenPoint(pos=(23,67))
point2 = ScreenPoint(pos=(239, 88))
point1.dragTo(point2)
```
something like this wold be useful. 
we can use the dragTo function present in pyautgui

**Comment by dingusagar** [comment]
oh okay, could you tell me which OS and python version you have?

**Comment by Power-PP** [comment]
Windowa 10 20H2 and python 3.7

**Comment by SaranshBaniyal** [comment]
@dingusagar  upon cloning it says that it cant find the module pyautoeasy as if its not installed

**Comment by dingusagar** [comment]
Okay, I am guessing it's because your current directory where pyautoeasy module is present is not added to the path where the python looks for whatever we are trying to import. This should have been taken care of usually by the IDE.

One thing you can try is to do relative imports. 
for eg:
from .pyautoeasy import ScreenPoint
"." tells to look in the current directory.  


If this doest work, another thing you can try is to programatically add the current directory in the python program. 

for eg,
 you can do something like this before importing the pyautoeasy,

import sys, os
sys.path.append('/path/to/pyautoeasy_repository)

from pyautoeasy import ScreenPoint


for reference : https://stackoverflow.com/questions/24722212/python-cant-find-module-in-the-same-folder

**Comment by SaranshBaniyal** [comment]
@dingusagar Thanks a lot, I'll give it a shot and let you know

**Comment by SaranshBaniyal** [comment]
@dingusagar Sorry man I was caught up in some personal matter so I didn't have the time to try it. I'll try to complete this as soon as I get free

**Comment by dingusagar** [comment]
Hey no worries. Take your time.

**Comment by SaranshBaniyal** [comment]
Hey, @dingusagar  I m sorry, I won't be able to continue, because of my college counselling schedule. But I would love to connect with you on any socials you have got available for future collaborations.

**Comment by dingusagar** [comment]
No worries @SaranshBaniyal . Will unassign you from this issue so that others can pick it up if interested. feel free to connect me via email or any other networks.

**Comment by rajan88lal88** [comment]
@dingusagar Can I take on this issue?

**Comment by dingusagar** [comment]
Thanks a lot @rajan88lal88 for the PR. Changes look good. Merging it.
