### ISSUE TITLE
Create a short screen-recording showing how to use pyautoeasy as an attempt to improving the documentation. 

### ISSUE THREAD

**Issue by dingusagar** [dingusagar/pyautoeasy#13]
we can even convert this video to a GIF and add it to the Readme file

**Comment by dingusagar** [comment]
Awesome, will assign it to you.

So this can be a short video (less than 2-3min if possible) describing how to easily create an automation script using this library.
you can try to think of some interesting use-case that we would like to automate by programing the mouse/keyboard.

One simple idea i was thinking of was to open a new tab in the browser and search for a topic, go to images and download the images one by one as an attempt to create an image dataset. All these can be easily automated by programming the mouse clicks/ keyboard typings using pyautoeasy. 

But if you have a better usecase in mind, please suggest, we can discuss and finalise it.
After finalising the usecase, record the video of the automation and we can add it to the examples folder in this repo. 

we can discuss how we want to upload the video file to this repo, if the video size is less than 10 MB, we can drag and drop it to a markdown file. or else we can even upload it to youtube and have the link in the readme file. 
 
Feel free to clarify any doubts / questions.

**Comment by dingusagar** [comment]
sure @SaranshBaniyal . you can post any doubts/issues you come across here as well.

**Comment by dingusagar** [comment]
@SaranshBaniyal ,
Could you open python shell from cmd and see  if it got installed properly.
 For this open cmd, type python and import pyautoeasy like this. 

```py
import pyautoeasy
```

Also if you have python2 also installed in your system. pip install would have installed it in your python2. If that's the issue, `pip3 install pyautoeasy`

If it's still not resolved, please send some screenshots of the error so that I can get a clearer picture of the issue.

**Comment by dingusagar** [comment]
Okay got it, not sure about how this happend in your system, but i think you might have tried to install python3.10 twice. 

So what happens is when you install python to some location, the path to this program gets added as an entry in the PATH environment variable. Any time you try to execute any command in cmd, it tries to check all the entries present in the PATH variable to locate the  correct executable file. 

Instead of moving the pyautoeasy.exe file, you can add this directory also as an entry in the PATH variable. 
you can follow the similar steps described in this [article](https://www.educative.io/edpresso/how-to-add-python-to-path-variable-in-windows).

Try this and let me know if you face any issues while doing this.

**Comment by dingusagar** [comment]
Since you were facing this issue,  i thought it would be good to have an alternative way to start the interactive program. 
So I pushed a fix here #18 and upgraded the version. 

So to start the program you could also do this from the cmd. 
```
python -m pyautoeasy
```

this is pushed in the latest version, so you have to install that. Anyways if you could fix the issue, that's good as well.
```
pip install pyautoeasy==0.0.5
```

**Comment by SaranshBaniyal** [comment]
Thanks a lot for the upgrade, it has started working

**Comment by SaranshBaniyal** [comment]
This is great, I ll push the video by afternoon positively. Sorry for the
delay
